/**
 * Playbook Estratégico Be Smart — conteúdo padrão (fonte: planosaude26-rgb.github.io/besmart, "Be Smart Arsenal").
 * Gerado a partir do site original; o bootstrap grava no banco (tabela playbook_entries), onde o conteúdo
 * passa a ser editável em /playbook por quem tem permissão settings:manage.
 */

export const PLAYBOOK_GROUPS = [
  { key: "modalidades", label: "Modalidades de plano", sections: ["pme", "adesao", "individual", "pj99"] },
  { key: "coberturas", label: "Coberturas", sections: ["atendimento", "acomodacao", "copart"] },
  { key: "comercial", label: "Comercial", sections: ["qualificacao", "spin", "ganchos", "followup"] },
] as const;

export const PLAYBOOK_SECTIONS: Record<string, { title: string; description: string }> = {
  pme: { title: "Plano Empresarial (PME)", description: "Contratação, vigência, carência, documentação, reajuste, cancelamento e preço" },
  adesao: { title: "Plano por Adesão", description: "Entidades de classe: sindicatos, associações e conselhos" },
  individual: { title: "Plano Individual (PF)", description: "Contratação direta como pessoa física" },
  pj99: { title: "Plano PJ (+99 vidas)", description: "Grandes empresas — capital global e estudo técnico" },
  atendimento: { title: "Segmentação assistencial", description: "Ambulatorial, hospitalar, obstetrícia e plano referência" },
  acomodacao: { title: "Acomodação na internação", description: "Enfermaria × apartamento" },
  copart: { title: "Modelos de coparticipação", description: "Total, parcial ou sem coparticipação" },
  qualificacao: { title: "Qualificação avançada", description: "Diagnóstico do cliente antes da cotação" },
  spin: { title: "Script SPIN Selling", description: "Situação, Problema, Implicação e Necessidade" },
  ganchos: { title: "Ganchos de venda", description: "Aberturas de alto impacto para WhatsApp e ligação" },
  followup: { title: "Estratégia de follow-up", description: "Cadência D0 → D7 — onde o dinheiro realmente é feito" },
};

export type PlaybookKind = "texto" | "roteiro";

export interface PlaybookEntryDef {
  section: string;
  key: string;
  title: string;
  subtitle: string | null;
  objective: string | null;
  /** "roteiro": cada linha do corpo é uma frase copiável isolada. */
  kind: PlaybookKind;
  body: string;
  sortOrder: number;
}

export const PLAYBOOK_DEFAULTS: PlaybookEntryDef[] = [
  {
    section: "pme",
    key: "contratacao",
    title: "Contratação",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "• Necessário CNPJ ativo (MEI mínimo 180 dias);\n• Mínimo de 2 ou 3 vidas conforme operadora;\n• Aceita Sócios, CLT, Estagiários e Dependentes.",
    sortOrder: 10,
  },
  {
    section: "pme",
    key: "vigencia",
    title: "Vigência",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "• Análise documental: 5 a 30 dias.\n• Vigência ativa somente após a quitação do primeiro boleto gerado pós-análise.",
    sortOrder: 20,
  },
  {
    section: "pme",
    key: "carencia",
    title: "Carência",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "• Urgência/emergência: 24 horas\n• Consultas e exames simples: 30 dias\n• Internações e exames complexos: 180 dias\n• Parto: 300 dias\n• Doenças e Lesões Pré-existentes (CPT): 24 meses.\n🔥 REDUÇÃO: Isenção total de carências para grupos acima de 30 vidas.\n\n💡 DICA DE NEGOCIAÇÃO:\nNa maioria das negociações, se o cliente tiver plano anterior, conseguimos fazer uma redução na carência dos planos contratados.",
    sortOrder: 30,
  },
  {
    section: "pme",
    key: "documentacao",
    title: "Documentação",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "🏢 EMPRESA / TITULAR:\n- CONTRATO SOCIAL\n- CNPJ\n- RG E CPF OU CNH DO TITULAR DO CNPJ\n- E-MAIL\n- TELEFONE\n\n👨‍👩‍👧‍👦 DEPENDENTES:\n- CERTIDÃO DE NASCIMENTO (SE FOR MENOR DE 18 ANOS)\n- RG E CPF OU CNH\n- VÍNCULO COM O TITULAR (CERTIDÃO DE CASAMENTO OU UNIÃO ESTÁVEL)\n\n👷 FUNCIONÁRIO:\n- RG E CPF OU CNH\n- COMPROVANTE DE VÍNCULO COM A EMPRESA (FGTS, E-SOCIAL, CARTEIRA DE TRABALHO)\n- E-MAIL\n- TELEFONE\n\n👨‍👩‍👧‍👦 DEPENDENTES DO FUNCIONÁRIO:\n- CERTIDÃO DE NASCIMENTO (SE FOR MENOR DE 18 ANOS)\n- RG E CPF OU CNH\n- VÍNCULO COM O TITULAR (CERTIDÃO DE CASAMENTO OU UNIÃO ESTÁVEL)\n\n⚠️ OBSERVAÇÃO:\nSe houver plano anterior, solicitar a Carta de Permanência.",
    sortOrder: 40,
  },
  {
    section: "pme",
    key: "reajuste",
    title: "Reajuste",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "• No aniversário do contrato (a cada 12 meses);\n• Taxa baseada na Sinistralidade (relação uso x prêmio pago).",
    sortOrder: 50,
  },
  {
    section: "pme",
    key: "cancelamento",
    title: "Cancelamento",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "• Fidelidade comum: 12 ou 24 meses.\n• Aviso prévio de 60 dias conforme RN 412 ANS.\n\n⚠️ ALERTA ESTRATÉGICO:\nSempre buscar uma melhor qualificação para o cliente não cancelar o plano antes de 6 meses (na maioria das operadoras) para evitar o estorno do comissionamento.",
    sortOrder: 60,
  },
  {
    section: "pme",
    key: "preco",
    title: "Análise de Preço",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "• Custo reduzido em relação ao individual.\n• Valores calculados por faixa etária ou capital global (acima de 99 vidas).",
    sortOrder: 70,
  },
  {
    section: "adesao",
    key: "contratacao",
    title: "Contratação",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "• Destinado a profissionais vinculados a entidades de classe (Sindicatos, Associações ou Conselhos).\n• Exige comprovação de vínculo (Diploma, Registro ou Carteirinha).",
    sortOrder: 80,
  },
  {
    section: "adesao",
    key: "vigencia",
    title: "Vigência",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "• Datas fixas de vigência (Ex: Todo dia 01, 10 ou 20 do mês).\n• Pagamento da taxa de Angariação na Assinatura do contrato.\n\n⚠️ IMPORTANTE:\nMesmo pagando a taxa de angariação, o cliente só estará coberto na data de vigência pré-definida na assinatura do contrato.",
    sortOrder: 90,
  },
  {
    section: "adesao",
    key: "carencia",
    title: "Carência",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "• Urgência/emergência: 24 horas\n• Consultas e exames simples: 30 dias\n• Internações e exames complexos: 180 dias\n• Parto: 300 dias\n• Doenças e Lesões Pré-existentes (CPT): 24 meses.\n\n💡 DICA DE NEGOCIAÇÃO:\nNa maioria das negociações, se o cliente tiver plano anterior, conseguimos fazer uma redução na carência dos planos contratados.",
    sortOrder: 100,
  },
  {
    section: "adesao",
    key: "documentacao",
    title: "Documentação",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "- RG e CPF ou CNH;\n- Selfie segurando um documento com foto;\n- Comprovante de Residência;\n- Comprovante de Vinculo à Entidade Associativa;\n- E-mail;\n- Telefone;\n- Carta de Permanência (Se houver plano anterior).\n\n👨‍👩‍👧‍👦 EM CASO DE DEPENDENTE:\n- RG e CPF ou CNH;\n- Comprovante de Vínculo com o Titular.\n\n⚠️ OBSERVAÇÃO:\nSe houver plano anterior, solicitar a Carta de Permanência.",
    sortOrder: 110,
  },
  {
    section: "adesao",
    key: "reajuste",
    title: "Reajuste",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "• No aniversário da apólice coletiva (mês fixo para todos daquela administradora).",
    sortOrder: 120,
  },
  {
    section: "adesao",
    key: "cancelamento",
    title: "Cancelamento",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "• Pode ser cancelado a qualquer momento.\n• REGRA DE OURO: Se for cancelado até um dia antes do vencimento, não é necessária a quitação do boleto, mesmo que já tenha sido emitido.",
    sortOrder: 130,
  },
  {
    section: "adesao",
    key: "preco",
    title: "Análise de Preço",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "• Custo intermediário entre o PME e o Individual PF.",
    sortOrder: 140,
  },
  {
    section: "individual",
    key: "contratacao",
    title: "Contratação",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "• Contratação direta como Pessoa Física (CPF);\n• Livre escolha sem necessidade de vínculo empresarial ou associativo.",
    sortOrder: 150,
  },
  {
    section: "individual",
    key: "vigencia",
    title: "Vigência",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "• Início imediato após confirmação bancária do pagamento do boleto de implantação (primeiro Boleto).",
    sortOrder: 160,
  },
  {
    section: "individual",
    key: "carencia",
    title: "Carência",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "• Urgência/emergência: 24 horas\n• Consultas e exames simples: 30 dias\n• Internações e exames complexos: 180 dias\n• Parto: 300 dias\n• Doenças e Lesões Pré-existentes (CPT): 24 meses.\n\n💡 DICA DE NEGOCIAÇÃO:\nNa maioria das negociações, se o cliente tiver plano anterior, conseguimos fazer uma redução na carência dos planos contratados.",
    sortOrder: 170,
  },
  {
    section: "individual",
    key: "documentacao",
    title: "Documentação",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "- RG e CPF ou CNH;\n- Selfie segurando um documento com foto;\n- Comprovante de Residência;\n- E-mail;\n- Telefone;\n- Carta de Permanência (Se houver plano anterior).\n\n👨‍👩‍👧‍👦 EM CASO DE DEPENDENTE:\n- RG e CPF ou CNH;\n- Comprovante de Vínculo com o Titular;\n- Carta de Permanência (Se houver plano anterior).\n\n⚠️ OBSERVAÇÃO:\nSe houver plano anterior, solicitar a Carta de Permanência.",
    sortOrder: 180,
  },
  {
    section: "individual",
    key: "reajuste",
    title: "Reajuste",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "• Aplicado no aniversário do contrato (a cada 12 meses de vigência);\n• Índice regulamentado e limitado pelo teto estabelecido pela ANS (Agência Nacional de Saúde).",
    sortOrder: 190,
  },
  {
    section: "individual",
    key: "cancelamento",
    title: "Cancelamento",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "• Pode ser cancelado a qualquer momento.\n• REGRA DE OURO: Se for cancelado até um dia antes do vencimento, não é necessária a quitação do boleto, mesmo que já tenha sido emitido.",
    sortOrder: 200,
  },
  {
    section: "individual",
    key: "preco",
    title: "Análise de Preço",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "• Maior estabilidade jurídica;\n• Valores tendem a ser superiores devido à proteção contratual da ANS.",
    sortOrder: 210,
  },
  {
    section: "pj99",
    key: "contratacao",
    title: "Contratação",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "• Destinado a grandes empresas com CNPJ ativo;\n• Mínimo de 100 vidas (titulares + dependentes);\n• Sempre uma negociação mais demorada.",
    sortOrder: 220,
  },
  {
    section: "pj99",
    key: "vigencia",
    title: "Vigência",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "• Datas negociadas diretamente com a operadora;\n• Geralmente vinculada à assinatura da apólice máster e implantação do grupo.",
    sortOrder: 230,
  },
  {
    section: "pj99",
    key: "carencia",
    title: "Carência",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "🔥 ISENÇÃO TOTAL:\nGrupos acima de 30 vidas possuem isenção total de carências, inclusive para CPT (Doenças Pré-existentes), conforme RN 195 da ANS.",
    sortOrder: 240,
  },
  {
    section: "pj99",
    key: "documentacao",
    title: "Documentação",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "🏢 EMPRESA / TITULAR:\n🔸 CONTRATO SOCIAL\n🔸 CNPJ\n🔸 RG E CPF OU CNH DO TITULAR DO CNPJ\n🔸 E-MAIL\n🔸 TELEFONE\n\n👨‍👩‍👧‍👦 DEPENDENTES:\n🔸 CERTIDÃO DE NASCIMENTO (SE FOR MENOR DE 18 ANOS)\n🔸 RG E CPF OU CNH\n🔸 VÍNCULO COM O TITULAR (CERTIDÃO DE CASAMENTO OU UNIÃO ESTÁVEL)\n\n👷 FUNCIONÁRIO:\n🔸 RG E CPF OU CNH\n🔸 COMPROVANTE DE VÍNCULO COM A EMPRESA (FGTS, E-SOCIAL, CARTEIRA DE TRABALHO)\n🔸 E-MAIL\n🔸 TELEFONE\n\n👨‍👩‍👧‍👦 DEPENDENTES DO FUNCIONÁRIO:\n🔸 CERTIDÃO DE NASCIMENTO (SE FOR MENOR DE 18 ANOS)\n🔸 RG E CPF OU CNH\n🔸 VÍNCULO COM O TITULAR (CERTIDÃO DE CASAMENTO OU UNIÃO ESTÁVEL)\n\n📊 ANÁLISE TÉCNICA E RISCO:\n🔸 RELATÓRIO DE SINISTRALIDADE DOS ÚLTIMOS 12 MESES;\n🔸 DATA DA RENOVAÇÃO;\n🔸 RELATÓRIO ANALÍTICO;\n🔸 RELAÇÃO DE VIDAS COMPLETA (Planilha EXCEL contendo obrigatoriamente as seguintes informações):\n  🔹 SEXO;\n  🔹 MUNICÍPIO / UF;\n  🔹 AFASTADOS (COM CIDs);\n  🔹 APOSENTADOS;\n  🔹 GESTANTES;\n🔸 PERFIL DE UTILIZAÇÃO - Alto uso ou baixo uso? Existência de: Internações recorrentes, Doenças crônicas (sem detalhar dados sensíveis individuais) e Gestante.\n🚨 *CARTA DE NOMEAÇÃO PARA AS OPERADORAS OU SEGURADORAS* 🚨\n🔸 10 MAIORES UTILIZADORES DOS PLANOS.",
    sortOrder: 250,
  },
  {
    section: "pj99",
    key: "reajuste",
    title: "Reajuste",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "• Reajuste Técnico (Loss Ratio): Baseado no equilíbrio financeiro específico daquela apólice (Prêmio x Utilização);\n• Negociação direta entre a empresa e a operadora.",
    sortOrder: 260,
  },
  {
    section: "pj99",
    key: "cancelamento",
    title: "Cancelamento",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "• Aviso prévio de 60 dias conforme RN 412 ANS;\n• Condições de rescisão regidas pelo contrato máster assinado entre as partes.",
    sortOrder: 270,
  },
  {
    section: "pj99",
    key: "preco",
    title: "Análise de Preço",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "• Estudo técnico personalizado (Capital Global);\n• Valores muito agressivos comparados a qualquer outra modalidade.",
    sortOrder: 280,
  },
  {
    section: "atendimento",
    key: "ambulatorial",
    title: "Ambulatorial",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "🏥 PLANO AMBULATORIAL:\nCobertura focada em atendimentos que não exigem internação.\n\n✅ O QUE COBRE:\n• Consultas médicas em clínicas e consultórios;\n• Exames laboratoriais e de imagem;\n• Tratamentos e procedimentos ambulatoriais;\n• Atendimentos de emergência limitados às primeiras 12 horas.\n\n❌ O QUE NÃO COBRE:\n• Internações hospitalares;\n• Cirurgias que exijam permanência em hospital;\n• Partos.\n\n💡 IDEAL PARA: Quem busca apenas acompanhamento de rotina e exames, com custo muito reduzido.",
    sortOrder: 290,
  },
  {
    section: "atendimento",
    key: "hospitalar",
    title: "Hospitalar",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "🏨 PLANO HOSPITALAR:\nCobertura focada exclusivamente em eventos de internação.\n\n✅ O QUE COBRE:\n• Internações hospitalares sem limite de dias;\n• Cirurgias e exames realizados durante a internação;\n• UTI e CTI;\n• Medicamentos ministrados durante o período hospitalar.\n\n❌ O QUE NÃO COBRE:\n• Consultas de rotina fora do hospital;\n• Exames preventivos ou de rotina (check-up);\n• Tratamentos ambulatoriais.\n\n💡 IDEAL PARA: Quem já tem um bom acompanhamento público ou particular para consultas, mas quer proteção contra custos altíssimos de hospitais.",
    sortOrder: 300,
  },
  {
    section: "atendimento",
    key: "sob",
    title: "Amb. + Hosp. sem Obstetrícia",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "⚖️ AMBULATORIAL + HOSPITALAR (SEM OBSTETRÍCIA):\nÉ a junção completa dos serviços, excluindo apenas o parto.\n\n✅ COBERTURA:\n• Consultas e exames (Ambulatorial);\n• Internações e cirurgias (Hospitalar).\n\n💡 VANTAGEM: Custo ligeiramente menor que o plano com obstetrícia.\n🎯 PÚBLICO: Homens, mulheres que não pretendem ter filhos ou pessoas fora da idade fértil.",
    sortOrder: 310,
  },
  {
    section: "atendimento",
    key: "cob",
    title: "Amb. + Hosp. com Obstetrícia",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "🤰 AMBULATORIAL + HOSPITALAR (COM OBSTETRÍCIA):\nA cobertura mais comum e equilibrada do mercado.\n\n✅ COBERTURA COMPLETA:\n• Consultas, exames, internações e cirurgias.\n• Assistência ao Parto (após cumprimento da carência de 300 dias).\n• Cobertura do recém-nascido nos primeiros 30 dias de vida.\n\n💡 IMPORTANTE: Garante a inclusão do bebê como dependente sem carências se solicitada em até 30 dias após o nascimento.",
    sortOrder: 320,
  },
  {
    section: "atendimento",
    key: "completo",
    title: "Plano Completo (Referência)",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "🌟 PLANO COMPLETO (REFERÊNCIA):\nO Plano Referência é definido pela Lei 9.656/98 e oferece o padrão ouro de segurança.\n\n💎 DIFERENCIAIS:\n• Segmentação Ambulatorial + Hospitalar com Obstetrícia;\n• Acomodação obrigatoriamente em Enfermaria (padrão lei);\n• Cobertura integral para urgência e emergência após 24h.\n\n💡 ARGUMENTO DE VENDA:\n\"É o plano que segue rigorosamente o padrão máximo exigido pela ANS, garantindo que você não fique na mão em nenhuma situação, desde uma consulta simples até um procedimento complexo de parto ou UTI.\"",
    sortOrder: 330,
  },
  {
    section: "acomodacao",
    key: "enfermaria",
    title: "Enfermaria (Coletivo)",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "👥 ENFERMARIA (QUARTO COLETIVO):\nAcomodação compartilhada com outros pacientes da mesma operadora.\n\n✅ CARACTERÍSTICAS:\n• Compartilhado com 2 ou mais pessoas (geralmente do mesmo sexo);\n• Banheiro também é compartilhado;\n• Horários de visita são mais restritos e limitados;\n• Acompanhante permitido apenas por lei (menores, idosos, gestantes).\n\n💰 VANTAGEM FINANCEIRA:\nO custo mensal do plano é cerca de 15% a 20% menor que o apartamento.\n\n💡 ARGUMENTO: Ideal para quem prioriza economia e não se importa com a falta de privacidade durante uma eventual internação.",
    sortOrder: 340,
  },
  {
    section: "acomodacao",
    key: "apartamento",
    title: "Apartamento (Privativo)",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "🏠 APARTAMENTO (QUARTO PRIVATIVO):\nAcomodação individual que oferece total privacidade e conforto.\n\n✅ CARACTERÍSTICAS:\n• Quarto individual exclusivo para o paciente;\n• Banheiro privativo no próprio quarto;\n• Horário de visitas muito mais flexível e estendido;\n• Direito a acompanhante 24h (muitas vezes com refeição incluída).\n\n💎 DIFERENCIAL DE CONFORTO:\nOferece maior tranquilidade para o paciente e para a família durante o processo de recuperação.\n\n💡 ARGUMENTO: Recomendado para quem valoriza privacidade, conforto absoluto e quer ter um familiar presente o tempo todo sem restrições.",
    sortOrder: 350,
  },
  {
    section: "acomodacao",
    key: "diferencas",
    title: "Quadro Comparativo",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "📊 QUADRO COMPARATIVO - RESUMO:\n\n📍 ENFERMARIA:\n• Privacidade: Baixa (Compartilhado)\n• Visitas: Horários rígidos\n• Acompanhante: Só por lei\n• Custo: Econômico (Mais barato)\n\n📍 APARTAMENTO:\n• Privacidade: Total (Individual)\n• Visitas: Horários flexíveis\n• Acompanhante: Permitido 24h\n• Custo: Prêmium (Investimento maior)\n\n🧠 DICA PARA O CLIENTE:\n\"Se você ou sua família costumam ter acompanhantes durante hospitalizações e prezam pelo conforto de um quarto exclusivo, o Apartamento é o ideal. Se o objetivo é a melhor proteção médica pelo menor preço possível, a Enfermaria atende perfeitamente.\"",
    sortOrder: 360,
  },
  {
    section: "copart",
    key: "total",
    title: "Coparticipação Total",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "🔴 COPARTICIPAÇÃO TOTAL - Definição Clara:\nCoparticipação total é o modelo de plano de saúde em que o cliente paga uma mensalidade mais baixa e participa com um percentual ou valor fixo em praticamente todos os atendimentos que utilizar.\n\n📊 COMO FUNCIONA NA PRÁTICA:\n• 💳 Mensalidade reduzida\n• 🩺 Cobrança ao usar: Consultas, Exames, Terapias e Procedimentos (em muitos casos)\n• 📈 Percentuais comuns: 20% a 50% (varia por operadora)\n• 🛑 Limite por evento e/ou teto mensal (proteção de custo)\n\n💡 EXPLICAÇÃO SIMPLES (PRA CLIENTE):\n\"Na coparticipação total você paga um valor menor todo mês e só participa com uma parte do custo quando usa o plano. Ou seja, não fica pagando caro sem utilizar — você investe conforme a necessidade.\"\n\n🎯 QUANDO FAZ SENTIDO:\n• 👤 Quem usa pouco o plano\n• 💰 Quem quer reduzir custo mensal\n• 📉 Quem prefere pagar sob demanda ao invés de fixo alto\n\n⚠️ PONTO DE ATENÇÃO:\nSe o cliente usa com muita frequência, esse modelo pode gerar mais custo ao longo do tempo — por isso a escolha precisa ser baseada no perfil.\n\n💬 FRASE DE VENDA (DIRETA):\n\"Esse modelo é ideal pra quem quer economizar no valor mensal e usar o plano de forma mais pontual, mantendo proteção quando precisar.\"",
    sortOrder: 370,
  },
  {
    section: "copart",
    key: "parcial",
    title: "Coparticipação Parcial",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "⚖️ COPARTICIPAÇÃO PARCIAL:\n• Taxas aplicadas apenas em itens específicos (geralmente Terapias e Internamentos).\n• Isenção total em Consultas Simples e Exames Laboratoriais básicos.\n\n🩺 PROCEDIMENTOS GERALMENTE COBRADOS:\n- Psicoterapias (sessões de psicologia).\n- Fisioterapias.\n- Fonoaudiologia.\n- Nutrição (consultas com nutricionista).\n- Terapia Ocupacional.\n\n• OBJETIVO: Equilíbrio entre uma mensalidade justa e liberdade de uso rotineiro.",
    sortOrder: 380,
  },
  {
    section: "copart",
    key: "sem",
    title: "Sem Coparticipação",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "🟢 SEM COPARTICIPAÇÃO - Explicação Clara:\nPlano sem coparticipação é aquele em que o cliente paga uma mensalidade fixa mais alta e não paga nada a mais quando utiliza os serviços cobertos.\n\n📊 COMO FUNCIONA NA PRÁTICA:\n• 💳 Mensalidade maior\n• 🩺 Sem cobrança por uso: Consultas, Exames, Internações e Procedimentos cobertos\n• 📉 Custo previsível (você sabe exatamente quanto vai pagar todo mês)\n\n💡 EXPLICAÇÃO SIMPLES (PRA CLIENTE):\n\"No plano sem coparticipação você paga um valor profissional por mês e pode usar consultas, exames e outros serviços sem pagar nada a mais por isso. É mais previsível, porque não tem surpresa no bolso quando precisar usar.\"\n\n🎯 QUANDO FAZ SENTIDO:\n• 👨‍👩‍👧 Quem usa o plano com frequência\n• 🩺 Pessoas com acompanhamento médico recorrente\n• 📅 Quem quer previsibilidade total no orçamento\n\n⚠️ PONTO DE ATENÇÃO:\nSe a pessoa quase não usa o plano, pode acabar pagando mais caro ao longo do tempo — já que a mensalidade é mais alta.\n\n💬 FRASE DE VENDA (DIRETA):\n\"Esse modelo é ideal pra quem quer tranquilidade total — você paga um valor profissional e usa o plano sem se preocupar com cobranças extras.\"\n\n🧠 COMO POSICIONAR BEM:\n👉 Não venda como \"mais caro\"\n👉 Venda como \"mais previsível e seguro\"",
    sortOrder: 390,
  },
  {
    section: "qualificacao",
    key: "perguntas",
    title: "Perguntas de qualificação",
    subtitle: "Diagnóstico cirúrgico Be Smart",
    objective: null,
    kind: "roteiro",
    body: "O plano seria só para você ou mais alguém da sua família vai aproveitar junto?\nPara eu conseguir calcular os melhores valores, qual a sua idade e a do pessoal que vai entrar?\nHoje vocês já têm algum plano de saúde ativo ou seria o primeiro?\nTem algum hospital, médico ou laboratório específico que você faz muita questão de ser atendido?\nVocê ou alguém da família tem algum CNPJ ativo? Pergunto porque até um MEI pode baixar bastante o valor do plano.\nQual a sua profissão ou área de formação? Dependendo da sua área, conseguimos descontos ótimos por sindicatos ou conselhos.\nPensando no CNPJ, você pretende incluir algum funcionário agora ou seria apenas para sócios e família?\nAlguém que vai entrar faz algum tratamento contínuo, precisa de cirurgia ou pretende engravidar em breve? É só pra eu buscar a melhor opção de carência para vocês.\nVocê já chegou a ver alguma cotação com outra pessoa? Pergunto para entender o que já te mostraram e buscar uma condição ainda melhor.",
    sortOrder: 400,
  },
  {
    section: "qualificacao",
    key: "dicas",
    title: "Dicas",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "• Não faça tudo de uma vez.\n• Conduza como conversa natural.\n• Escute mais do que fala.",
    sortOrder: 410,
  },
  {
    section: "spin",
    key: "s",
    title: "S — Situação",
    subtitle: "Entender o cenário atual do cliente.",
    objective: null,
    kind: "roteiro",
    body: "Hoje você já tem plano de saúde ou ainda não?\nÉ só pra você ou mais alguém da família?\nQual sua idade e cidade?\nHoje você usa bastante plano ou é mais segurança?",
    sortOrder: 420,
  },
  {
    section: "spin",
    key: "p",
    title: "P — Problema",
    subtitle: "Identificar as dores reais.",
    objective: null,
    kind: "roteiro",
    body: "O que te fez ainda não contratar um plano?\nO que te incomoda no seu plano atual?\nVocê sente que paga justo ou poderia ser melhor?\nSe acontecer uma emergência hoje, como você resolveria?",
    sortOrder: 430,
  },
  {
    section: "spin",
    key: "i",
    title: "I — Implicação",
    subtitle: "Aumentar o peso e a urgência do problema.",
    objective: null,
    kind: "roteiro",
    body: "E se você precisar usar e não tiver cobertura adequada, isso te geraria problema?\nSe continuar pagando esse valor alto, quanto isso pesa no orçamento ao longo do ano?\nSe acontecer algo com alguém da sua família, como isso impacta você hoje?",
    sortOrder: 440,
  },
  {
    section: "spin",
    key: "n",
    title: "N — Necessidade",
    subtitle: "Fazer o cliente desejar a sua solução.",
    objective: null,
    kind: "roteiro",
    body: "Se eu te mostrar uma opção que resolva isso, faz sentido pra você?\nO ideal pra você hoje seria pagar menos ou ter mais segurança?\nSe encaixar no que você precisa, você fecharia agora?",
    sortOrder: 450,
  },
  {
    section: "ganchos",
    key: "ganchos_de_dor",
    title: "🔥 Ganchos de dor",
    subtitle: "Quando o cliente não tem plano ou está inseguro",
    objective: "Gerar desconforto e consciência",
    kind: "roteiro",
    body: "Deixa eu te fazer uma pergunta rápida: se você precisar de atendimento hoje, você tá tranquilo ou seria um problema financeiro?\nVocê já percebeu como qualquer emergência hoje pode virar uma dívida gigante?\nA maioria das pessoas só procura plano depois que precisa... você prefere se antecipar ou correr esse risco?",
    sortOrder: 460,
  },
  {
    section: "ganchos",
    key: "ganchos_de_economia",
    title: "💰 Ganchos de economia",
    subtitle: "Perfeito pra quem já tem plano ou acha caro",
    objective: "Abrir conversa sem resistência",
    kind: "roteiro",
    body: "Hoje você sente que paga justo no seu plano ou acha que pode estar pagando mais do que deveria?\nSe eu te mostrar uma forma de manter ou melhorar seu plano pagando menos, faz sentido pra você?\nPosso te mostrar como algumas pessoas estão economizando até 30% no plano sem perder cobertura?",
    sortOrder: 470,
  },
  {
    section: "ganchos",
    key: "ganchos_de_urgencia",
    title: "⚡ Ganchos de urgência",
    subtitle: "Funciona muito bem em campanhas ou follow-up",
    objective: "Acelerar decisão",
    kind: "roteiro",
    body: "Te chamei porque essa semana tivemos atualização nas tabelas e pode impactar direto no valor do seu plano.\nAlguns planos estão mudando regras de entrada... você já está protegido ou ainda está vendo isso?\nSe você decidir depois, pode acabar pagando mais caro ou pegando mais carência.",
    sortOrder: 480,
  },
  {
    section: "ganchos",
    key: "ganchos_de_curiosidade",
    title: "🧠 Ganchos de curiosidade",
    subtitle: "Ótimo pra iniciar conversa no whatsapp",
    objective: "Fazer o cliente responder",
    kind: "roteiro",
    body: "Posso te mostrar um erro comum que faz as pessoas pagarem caro em plano de saúde sem perceber?\nVocê sabia que existem 3 tipos de plano e a maioria das pessoas escolhe o errado?\nTem um detalhe no plano de saúde que quase ninguém te explica... quer ver?",
    sortOrder: 490,
  },
  {
    section: "ganchos",
    key: "seguranca_familia",
    title: "🛡️ Segurança / família",
    subtitle: "Muito forte emocionalmente",
    objective: "Ativar emoção + responsabilidade",
    kind: "roteiro",
    body: "Hoje você e sua família estão realmente protegidos em caso de emergência?\nSe acontecer alguma coisa com alguém próximo, você prefere depender do SUS ou ter mais segurança?\nPlano de saúde não é gasto... é proteção. Você já garantiu isso pra sua família?",
    sortOrder: 500,
  },
  {
    section: "ganchos",
    key: "ganchos_de_troca",
    title: "🔄 Ganchos de troca",
    subtitle: "Portabilidade - para quem já tem plano",
    objective: "Abrir brecha sem parecer agressivo",
    kind: "roteiro",
    body: "Você sabia que pode melhorar seu plano sem cumprir carência dependendo do seu caso?\nPosso analisar seu plano atual e te mostrar se você está bem posicionado ou perdendo dinheiro?\nMuita gente não sabe, mas dá pra trocar de plano e manter os benefícios... quer ver como funciona?",
    sortOrder: 510,
  },
  {
    section: "ganchos",
    key: "gancho_direto",
    title: "🎯 Gancho direto",
    subtitle: "Estilo fechador - ir direto ao ponto",
    objective: "Qualificar rápido",
    kind: "roteiro",
    body: "Me diz uma coisa: hoje o que pesa mais pra você num plano — preço, rede ou cobertura?\nSe eu encontrar um plano que encaixe no seu orçamento, você contrataria agora ou ainda está só pesquisando?",
    sortOrder: 520,
  },
  {
    section: "followup",
    key: "regra_de_ouro",
    title: "Regra de ouro",
    subtitle: null,
    objective: null,
    kind: "texto",
    body: "O dinheiro está no acompanhamento, não no primeiro contato. Quem não faz follow-up organizado, vive de sorte.",
    sortOrder: 530,
  },
  {
    section: "followup",
    key: "d0",
    title: "D0 — Primeiro contato",
    subtitle: "Envio da proposta",
    objective: "Deixar o canal aberto",
    kind: "roteiro",
    body: "Fala, [Nome]! Conforme conversamos, te enviei as opções de plano de saúde com melhor custo-benefício. Separei pensando no que você me falou. Dá uma olhada com calma e qualquer dúvida me chama 👍",
    sortOrder: 540,
  },
  {
    section: "followup",
    key: "d1",
    title: "D1 — Check-in",
    subtitle: "1 dia depois",
    objective: "Saber se conseguiu ler",
    kind: "roteiro",
    body: "Oi, [Nome]! Conseguiu dar uma olhada nas opções que te mandei? Se quiser, posso te indicar direto a melhor escolha pra você baseado no que você precisa.",
    sortOrder: 550,
  },
  {
    section: "followup",
    key: "d3",
    title: "D3 — Objeção silenciosa",
    subtitle: "3 dias depois",
    objective: "Identificar travas de preço/rede",
    kind: "roteiro",
    body: "[Nome], muitos clientes meus ficam na dúvida nessa etapa entre preço e qualidade. Se for o seu caso, me fala o que tá pesando mais aí que eu te ajudo a ajustar.",
    sortOrder: 560,
  },
  {
    section: "followup",
    key: "d5",
    title: "D5 — Urgência / especificidade",
    subtitle: "5 dias depois",
    objective: "Acelerar o fechamento",
    kind: "roteiro",
    body: "[Nome], só um ponto importante: alguns planos podem sofrer reajuste nos próximos dias. Vale a pena já garantir nessas condições. Posso te ajudar com isso agora?",
    sortOrder: 570,
  },
  {
    section: "followup",
    key: "d7",
    title: "D7 — Despedida elegante",
    subtitle: "7 dias depois",
    objective: "Limpar o funil / tirar pressão",
    kind: "roteiro",
    body: "[Nome], não sei se você já resolveu a questão do plano de saúde. Se ainda estiver vendo isso, posso te ajudar. Se já resolveu, me avisa também 👍",
    sortOrder: 580,
  },
];
